PKG_NAME = faac
PKG_VERS = 1.28
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://downloads.sourceforge.net/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://www.audiocoding.com
COMMENT  = 
LICENSE  = GPL2

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
