PKG_NAME = nma
PKG_VERS = 0.3
PKG_EXT = tar.xz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://christian.users.heimdaheim.de/nma
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/openssl

HOMEPAGE = http://www.notifymyandroid.com
COMMENT  = API interface for NotifyMyAndroid
LICENSE  = GPL

GNU_CONFIGURE=1

include ../../mk/spksrc.cross-cc.mk
